version: '3.9'
services:
  api:
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      PORT: ${API_PORT}
      MONGO_DB_URL: ${MONGO_DB_URL}

  client:
    image: client_ecom
    build:
      context: ./client/.
      dockerfile: Dockerfile
    ports:
      - 3003:3000
    environment:
      BACKEND_URL: ${BACKEND_URL}
